export default {
  REQUEST_USERS: 'REQUEST_USERS',
  RECEIVE_USERS: 'RECEIVE_USERS',
  FILTER_USERS: 'FILTER_USERS',

  BEGIN_LOGIN: 'BEGIN_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  REQUEST_MESSAGES: 'REQUEST_MESSAGES',
  RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',

  BEGIN_REGISTRATION: 'BEGIN_REGISTRATION',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILURE: 'REGISTRATION_FAILURE'
}
